// @contact.name API Support

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

package gin

import (
	"github.com/PittYao/stream_gateway/components/config"
	"github.com/PittYao/stream_gateway/internal/router"
	"github.com/PittYao/stream_gateway/internal/router/docs"
	"net/http"

	// docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

const (
	// DisableGinSwaggerEnvKey 设置该环境变量时关闭 swagger 文档
	DisableGinSwaggerEnvKey = "DISABLE_GIN_SWAGGER_dd"
)

// RegisterRouter 注册swagger路由
func RegisterRouter(httpHandler http.Handler) {
	app, ok := httpHandler.(*gin.Engine)
	if !ok {
		panic("HTTP handler must be *ginconfig.Engine")
	}

	// 注册Swagger路由 swagger 文档变量设置
	docs.SwaggerInfo.Title = config.C.Swagger.Title
	docs.SwaggerInfo.Description = config.C.Swagger.Desc
	//docs.SwaggerInfo.Host = config.C.Server.Ip + config.C.Server.Port
	docs.SwaggerInfo.BasePath = config.C.Swagger.BasePath
	docs.SwaggerInfo.Schemes = config.C.Swagger.Schemes

	app.GET(config.C.Swagger.Url+"/*any", ginSwagger.DisablingWrapHandler(swaggerFiles.Handler, DisableGinSwaggerEnvKey))

	// 注册业务路由
	router.Routes(app)
}
