definitions:
  dto.StartMix3Req:
    properties:
      roomName:
        example: "1"
        type: string
      rtspUrlLeft:
        example: rtsp://admin:cebon61332433@192.168.99.215:554/cam/realmonitor?channel=1&subtype=1
        type: string
      rtspUrlMiddle:
        example: rtsp://admin:cebon61332433@192.168.99.215:554/cam/realmonitor?channel=1&subtype=0
        type: string
      rtspUrlRight:
        example: rtsp://admin:cebon61332433@192.168.99.215:554/cam/realmonitor?channel=1&subtype=1
        type: string
      temperature:
        example: ""
        type: string
    required:
    - rtspUrlLeft
    - rtspUrlMiddle
    - rtspUrlRight
    type: object
  dto.StopReq:
    properties:
      rtmpUrl:
        type: string
      taskId:
        type: integer
    required:
    - rtmpUrl
    - taskId
    type: object
  response.Response:
    properties:
      code:
        description: 响应码
        type: integer
      data:
        description: 响应数据
      msg:
        description: 响应消息
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/mix/transform/save/listAll:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询所有
      tags:
      - 三合一
  /api/v1/mix/transform/save/rebootAll:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 重启所有
      tags:
      - 三合一
  /api/v1/mix/transform/save/start:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: startMix3Req
        required: true
        schema:
          $ref: '#/definitions/dto.StartMix3Req'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 开始
      tags:
      - 三合一
  /api/v1/mix/transform/save/stop:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: stopReq
        required: true
        schema:
          $ref: '#/definitions/dto.StopReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 停止
      tags:
      - 三合一
  /api/v1/mix/transform/save/stopAll:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 停止所有
      tags:
      - 三合一
swagger: "2.0"
