server:
  profile: dev
  name: gateway
  ip: 127.0.0.1
  port: 8082

log:
  dir: logs
  maxSize: 200
  maxAge: 90
  maxBackups: 100
  compress: true
  localtime: true
  showLine: true

mysql:
  conn_max_lifetime: 1h
  max_idle_conns: 1
  max_open_conns: 10

swagger:
#  http://localhost:8080/doc/index.html
  title: 视频存储服务网关文档
  desc: 网关
  host: ""
  url: /doc
  basePath: /
  schemes:
    - http


